# Build stage
FROM node:14-alpine AS builder

WORKDIR /usr/tmp
COPY . /usr/tmp

RUN apk update && apk upgrade
RUN npm install -g npm@latest
RUN npm install

ENV NODE_ENV=production
RUN npm run build-common
RUN npm run build --workspace=@tipovacka/api

# Production stage
FROM node:14-alpine

WORKDIR /usr/src
COPY --from=builder /usr/tmp/apps/api/dist/ /usr/src

EXPOSE 3003

CMD [ "node", "index.js" ]
