FROM node:14-alpine

WORKDIR /usr/tmp

RUN apk update && apk upgrade

COPY . /usr/tmp

RUN npm install -g npm@latest
RUN npm install

ENV NODE_ENV=production
RUN npm run build-common
RUN npm run build --workspace=@tipovacka/api

WORKDIR /usr/src
RUN mv /usr/tmp/apps/api/dist/* /usr/src

RUN rm -rf ./tmp

EXPOSE 3003

CMD [ "node", "index.js" ]
