# Build stage
FROM node:14-alpine AS builder

WORKDIR /usr/tmp
COPY . .

RUN apk update && apk upgrade
RUN npm install -g npm@latest
RUN npm install

RUN npm run build-common
RUN npx nuxt build --standalone

# Production stage
FROM node:14-alpine

WORKDIR /usr/src

COPY --from=builder /usr/tmp/apps/client/.nuxt ./.nuxt
COPY --from=builder /usr/tmp/apps/client/package.json ./package.json
COPY --from=builder /usr/tmp/apps/client/nuxt.config.js ./nuxt.config.js
COPY --from=builder /usr/tmp/apps/client/static ./static

RUN npm install --production
RUN npm install nuxt-start
RUN ls -al

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

EXPOSE 3000

CMD [ "npx", "nuxt-start" ]
